/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Artifact {
  'id' : ArtifactId,
  'cid' : string,
  'verified' : boolean,
  'artifactType' : ArtifactType,
  'contentHash' : string,
  'timestamp' : Timestamp,
  'uploadedBy' : Principal,
}
export type ArtifactId = string;
export type ArtifactType = { 'ModelWeights' : null } |
  { 'Kernel' : null } |
  { 'Dataset' : null } |
  { 'Config' : null };
export interface EggrollParams {
  'r' : bigint,
  'alpha' : number,
  'epochs' : bigint,
  'nPopulation' : bigint,
}
export interface GenerationResult {
  'bestFitness' : number,
  'generation' : bigint,
  'taskId' : TaskId,
  'timestamp' : Timestamp,
  'averageFitness' : number,
  'workerCount' : bigint,
}
export interface ProtocolStats {
  'currentGeneration' : bigint,
  'completedTasks' : bigint,
  'totalWorkers' : bigint,
  'activeWorkers' : bigint,
  'pendingTasks' : bigint,
}
export interface Task {
  'id' : TaskId,
  'modelArtifactId' : ArtifactId,
  'status' : TaskStatus,
  'currentGeneration' : bigint,
  'datasetArtifactId' : ArtifactId,
  'createdAt' : Timestamp,
  'createdBy' : Principal,
  'totalGenerations' : bigint,
  'updatedAt' : Timestamp,
  'params' : EggrollParams,
}
export type TaskId = string;
export type TaskStatus = { 'Active' : null } |
  { 'Cancelled' : null } |
  { 'Completed' : null } |
  { 'Pending' : null };
export type Timestamp = bigint;
export interface Worker {
  'id' : Principal,
  'elo' : number,
  'status' : WorkerStatus,
  'slashCount' : bigint,
  'lastSubmission' : [] | [Timestamp],
  'totalSubmissions' : bigint,
}
export type WorkerStatus = { 'Inactive' : null } |
  { 'Active' : null } |
  { 'Slashed' : null };
export interface WorkerSubmission {
  'workerId' : Principal,
  'generation' : bigint,
  'taskId' : TaskId,
  'fitness' : number,
  'timestamp' : Timestamp,
}
export interface _SERVICE {
  'createTask' : ActorMethod<
    [string, string, EggrollParams, bigint],
    { 'ok' : Task } |
      { 'err' : string }
  >,
  'getArtifact' : ActorMethod<[string], [] | [Artifact]>,
  'getArtifacts' : ActorMethod<[], Array<Artifact>>,
  'getStats' : ActorMethod<[], ProtocolStats>,
  'getTask' : ActorMethod<[string], [] | [Task]>,
  'getTaskGenerations' : ActorMethod<[string], Array<GenerationResult>>,
  'getTaskSubmissions' : ActorMethod<[string], Array<WorkerSubmission>>,
  'getTasks' : ActorMethod<[], Array<Task>>,
  'getWorker' : ActorMethod<[Principal], [] | [Worker]>,
  'getWorkers' : ActorMethod<[], Array<Worker>>,
  'registerArtifact' : ActorMethod<
    [ArtifactType, string, string],
    { 'ok' : Artifact } |
      { 'err' : string }
  >,
  'registerWorker' : ActorMethod<[], { 'ok' : Worker } | { 'err' : string }>,
  'submitFitness' : ActorMethod<
    [string, bigint, number],
    { 'ok' : null } |
      { 'err' : string }
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];