/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const EggrollParams = IDL.Record({
  'r' : IDL.Nat,
  'alpha' : IDL.Float64,
  'epochs' : IDL.Nat,
  'nPopulation' : IDL.Nat,
});
export const TaskId = IDL.Text;
export const ArtifactId = IDL.Text;
export const TaskStatus = IDL.Variant({
  'Active' : IDL.Null,
  'Cancelled' : IDL.Null,
  'Completed' : IDL.Null,
  'Pending' : IDL.Null,
});
export const Timestamp = IDL.Nat64;
export const Task = IDL.Record({
  'id' : TaskId,
  'modelArtifactId' : ArtifactId,
  'status' : TaskStatus,
  'currentGeneration' : IDL.Nat,
  'datasetArtifactId' : ArtifactId,
  'createdAt' : Timestamp,
  'createdBy' : IDL.Principal,
  'totalGenerations' : IDL.Nat,
  'updatedAt' : Timestamp,
  'params' : EggrollParams,
});
export const ArtifactType = IDL.Variant({
  'ModelWeights' : IDL.Null,
  'Kernel' : IDL.Null,
  'Dataset' : IDL.Null,
  'Config' : IDL.Null,
});
export const Artifact = IDL.Record({
  'id' : ArtifactId,
  'cid' : IDL.Text,
  'verified' : IDL.Bool,
  'artifactType' : ArtifactType,
  'contentHash' : IDL.Text,
  'timestamp' : Timestamp,
  'uploadedBy' : IDL.Principal,
});
export const ProtocolStats = IDL.Record({
  'currentGeneration' : IDL.Nat,
  'completedTasks' : IDL.Nat,
  'totalWorkers' : IDL.Nat,
  'activeWorkers' : IDL.Nat,
  'pendingTasks' : IDL.Nat,
});
export const GenerationResult = IDL.Record({
  'bestFitness' : IDL.Float64,
  'generation' : IDL.Nat,
  'taskId' : TaskId,
  'timestamp' : Timestamp,
  'averageFitness' : IDL.Float64,
  'workerCount' : IDL.Nat,
});
export const WorkerSubmission = IDL.Record({
  'workerId' : IDL.Principal,
  'generation' : IDL.Nat,
  'taskId' : TaskId,
  'fitness' : IDL.Float64,
  'timestamp' : Timestamp,
});
export const WorkerStatus = IDL.Variant({
  'Inactive' : IDL.Null,
  'Active' : IDL.Null,
  'Slashed' : IDL.Null,
});
export const Worker = IDL.Record({
  'id' : IDL.Principal,
  'elo' : IDL.Float64,
  'status' : WorkerStatus,
  'slashCount' : IDL.Nat,
  'lastSubmission' : IDL.Opt(Timestamp),
  'totalSubmissions' : IDL.Nat,
});

export const idlService = IDL.Service({
  'createTask' : IDL.Func(
      [IDL.Text, IDL.Text, EggrollParams, IDL.Nat],
      [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
      [],
    ),
  'getArtifact' : IDL.Func([IDL.Text], [IDL.Opt(Artifact)], ['query']),
  'getArtifacts' : IDL.Func([], [IDL.Vec(Artifact)], ['query']),
  'getStats' : IDL.Func([], [ProtocolStats], ['query']),
  'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
  'getTaskGenerations' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GenerationResult)],
      ['query'],
    ),
  'getTaskSubmissions' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(WorkerSubmission)],
      ['query'],
    ),
  'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
  'getWorker' : IDL.Func([IDL.Principal], [IDL.Opt(Worker)], ['query']),
  'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
  'registerArtifact' : IDL.Func(
      [ArtifactType, IDL.Text, IDL.Text],
      [IDL.Variant({ 'ok' : Artifact, 'err' : IDL.Text })],
      [],
    ),
  'registerWorker' : IDL.Func(
      [],
      [IDL.Variant({ 'ok' : Worker, 'err' : IDL.Text })],
      [],
    ),
  'submitFitness' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Float64],
      [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const EggrollParams = IDL.Record({
    'r' : IDL.Nat,
    'alpha' : IDL.Float64,
    'epochs' : IDL.Nat,
    'nPopulation' : IDL.Nat,
  });
  const TaskId = IDL.Text;
  const ArtifactId = IDL.Text;
  const TaskStatus = IDL.Variant({
    'Active' : IDL.Null,
    'Cancelled' : IDL.Null,
    'Completed' : IDL.Null,
    'Pending' : IDL.Null,
  });
  const Timestamp = IDL.Nat64;
  const Task = IDL.Record({
    'id' : TaskId,
    'modelArtifactId' : ArtifactId,
    'status' : TaskStatus,
    'currentGeneration' : IDL.Nat,
    'datasetArtifactId' : ArtifactId,
    'createdAt' : Timestamp,
    'createdBy' : IDL.Principal,
    'totalGenerations' : IDL.Nat,
    'updatedAt' : Timestamp,
    'params' : EggrollParams,
  });
  const ArtifactType = IDL.Variant({
    'ModelWeights' : IDL.Null,
    'Kernel' : IDL.Null,
    'Dataset' : IDL.Null,
    'Config' : IDL.Null,
  });
  const Artifact = IDL.Record({
    'id' : ArtifactId,
    'cid' : IDL.Text,
    'verified' : IDL.Bool,
    'artifactType' : ArtifactType,
    'contentHash' : IDL.Text,
    'timestamp' : Timestamp,
    'uploadedBy' : IDL.Principal,
  });
  const ProtocolStats = IDL.Record({
    'currentGeneration' : IDL.Nat,
    'completedTasks' : IDL.Nat,
    'totalWorkers' : IDL.Nat,
    'activeWorkers' : IDL.Nat,
    'pendingTasks' : IDL.Nat,
  });
  const GenerationResult = IDL.Record({
    'bestFitness' : IDL.Float64,
    'generation' : IDL.Nat,
    'taskId' : TaskId,
    'timestamp' : Timestamp,
    'averageFitness' : IDL.Float64,
    'workerCount' : IDL.Nat,
  });
  const WorkerSubmission = IDL.Record({
    'workerId' : IDL.Principal,
    'generation' : IDL.Nat,
    'taskId' : TaskId,
    'fitness' : IDL.Float64,
    'timestamp' : Timestamp,
  });
  const WorkerStatus = IDL.Variant({
    'Inactive' : IDL.Null,
    'Active' : IDL.Null,
    'Slashed' : IDL.Null,
  });
  const Worker = IDL.Record({
    'id' : IDL.Principal,
    'elo' : IDL.Float64,
    'status' : WorkerStatus,
    'slashCount' : IDL.Nat,
    'lastSubmission' : IDL.Opt(Timestamp),
    'totalSubmissions' : IDL.Nat,
  });
  
  return IDL.Service({
    'createTask' : IDL.Func(
        [IDL.Text, IDL.Text, EggrollParams, IDL.Nat],
        [IDL.Variant({ 'ok' : Task, 'err' : IDL.Text })],
        [],
      ),
    'getArtifact' : IDL.Func([IDL.Text], [IDL.Opt(Artifact)], ['query']),
    'getArtifacts' : IDL.Func([], [IDL.Vec(Artifact)], ['query']),
    'getStats' : IDL.Func([], [ProtocolStats], ['query']),
    'getTask' : IDL.Func([IDL.Text], [IDL.Opt(Task)], ['query']),
    'getTaskGenerations' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GenerationResult)],
        ['query'],
      ),
    'getTaskSubmissions' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(WorkerSubmission)],
        ['query'],
      ),
    'getTasks' : IDL.Func([], [IDL.Vec(Task)], ['query']),
    'getWorker' : IDL.Func([IDL.Principal], [IDL.Opt(Worker)], ['query']),
    'getWorkers' : IDL.Func([], [IDL.Vec(Worker)], ['query']),
    'registerArtifact' : IDL.Func(
        [ArtifactType, IDL.Text, IDL.Text],
        [IDL.Variant({ 'ok' : Artifact, 'err' : IDL.Text })],
        [],
      ),
    'registerWorker' : IDL.Func(
        [],
        [IDL.Variant({ 'ok' : Worker, 'err' : IDL.Text })],
        [],
      ),
    'submitFitness' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Float64],
        [IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text })],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };