/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Artifact {
    id: ArtifactId;
    cid: string;
    verified: boolean;
    artifactType: ArtifactType;
    contentHash: string;
    timestamp: Timestamp;
    uploadedBy: Principal;
}
export type Timestamp = bigint;
export interface WorkerSubmission {
    workerId: Principal;
    generation: bigint;
    taskId: TaskId;
    fitness: number;
    timestamp: Timestamp;
}
export type TaskId = string;
export interface Task {
    id: TaskId;
    modelArtifactId: ArtifactId;
    status: TaskStatus;
    currentGeneration: bigint;
    datasetArtifactId: ArtifactId;
    createdAt: Timestamp;
    createdBy: Principal;
    totalGenerations: bigint;
    updatedAt: Timestamp;
    params: EggrollParams;
}
export interface ProtocolStats {
    currentGeneration: bigint;
    completedTasks: bigint;
    totalWorkers: bigint;
    activeWorkers: bigint;
    pendingTasks: bigint;
}
export interface EggrollParams {
    r: bigint;
    alpha: number;
    epochs: bigint;
    nPopulation: bigint;
}
export interface Worker {
    id: Principal;
    elo: number;
    status: WorkerStatus;
    slashCount: bigint;
    lastSubmission?: Timestamp;
    totalSubmissions: bigint;
}
export interface GenerationResult {
    bestFitness: number;
    generation: bigint;
    taskId: TaskId;
    timestamp: Timestamp;
    averageFitness: number;
    workerCount: bigint;
}
export type ArtifactId = string;
export enum ArtifactType {
    ModelWeights = "ModelWeights",
    Kernel = "Kernel",
    Dataset = "Dataset",
    Config = "Config"
}
export enum TaskStatus {
    Active = "Active",
    Cancelled = "Cancelled",
    Completed = "Completed",
    Pending = "Pending"
}
export enum WorkerStatus {
    Inactive = "Inactive",
    Active = "Active",
    Slashed = "Slashed"
}
export interface backendInterface {
    createTask(modelArtifactId: string, datasetArtifactId: string, params: EggrollParams, totalGenerations: bigint): Promise<{
        __kind__: "ok";
        ok: Task;
    } | {
        __kind__: "err";
        err: string;
    }>;
    getArtifact(id: string): Promise<Artifact | null>;
    getArtifacts(): Promise<Array<Artifact>>;
    getStats(): Promise<ProtocolStats>;
    getTask(id: string): Promise<Task | null>;
    getTaskGenerations(taskId: string): Promise<Array<GenerationResult>>;
    getTaskSubmissions(taskId: string): Promise<Array<WorkerSubmission>>;
    getTasks(): Promise<Array<Task>>;
    getWorker(id: Principal): Promise<Worker | null>;
    getWorkers(): Promise<Array<Worker>>;
    registerArtifact(artifactType: ArtifactType, contentHash: string, cid: string): Promise<{
        __kind__: "ok";
        ok: Artifact;
    } | {
        __kind__: "err";
        err: string;
    }>;
    registerWorker(): Promise<{
        __kind__: "ok";
        ok: Worker;
    } | {
        __kind__: "err";
        err: string;
    }>;
    submitFitness(taskId: string, generation: bigint, fitness: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }>;
}
import type { Artifact as _Artifact, ArtifactId as _ArtifactId, ArtifactType as _ArtifactType, EggrollParams as _EggrollParams, Task as _Task, TaskId as _TaskId, TaskStatus as _TaskStatus, Timestamp as _Timestamp, Worker as _Worker, WorkerStatus as _WorkerStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async createTask(arg0: string, arg1: string, arg2: EggrollParams, arg3: bigint): Promise<{
        __kind__: "ok";
        ok: Task;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.createTask(arg0, arg1, arg2, arg3);
                return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createTask(arg0, arg1, arg2, arg3);
            return from_candid_variant_n1(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtifact(arg0: string): Promise<Artifact | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtifact(arg0);
                return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtifact(arg0);
            return from_candid_opt_n6(this._uploadFile, this._downloadFile, result);
        }
    }
    async getArtifacts(): Promise<Array<Artifact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getArtifacts();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getArtifacts();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getStats(): Promise<ProtocolStats> {
        if (this.processError) {
            try {
                const result = await this.actor.getStats();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getStats();
            return result;
        }
    }
    async getTask(arg0: string): Promise<Task | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getTask(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTask(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getTaskGenerations(arg0: string): Promise<Array<GenerationResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskGenerations(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskGenerations(arg0);
            return result;
        }
    }
    async getTaskSubmissions(arg0: string): Promise<Array<WorkerSubmission>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTaskSubmissions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTaskSubmissions(arg0);
            return result;
        }
    }
    async getTasks(): Promise<Array<Task>> {
        if (this.processError) {
            try {
                const result = await this.actor.getTasks();
                return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTasks();
            return from_candid_vec_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorker(arg0: Principal): Promise<Worker | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorker(arg0);
                return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorker(arg0);
            return from_candid_opt_n14(this._uploadFile, this._downloadFile, result);
        }
    }
    async getWorkers(): Promise<Array<Worker>> {
        if (this.processError) {
            try {
                const result = await this.actor.getWorkers();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getWorkers();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerArtifact(arg0: ArtifactType, arg1: string, arg2: string): Promise<{
        __kind__: "ok";
        ok: Artifact;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerArtifact(to_candid_ArtifactType_n21(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
                return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerArtifact(to_candid_ArtifactType_n21(this._uploadFile, this._downloadFile, arg0), arg1, arg2);
            return from_candid_variant_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerWorker(): Promise<{
        __kind__: "ok";
        ok: Worker;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.registerWorker();
                return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerWorker();
            return from_candid_variant_n24(this._uploadFile, this._downloadFile, result);
        }
    }
    async submitFitness(arg0: string, arg1: bigint, arg2: number): Promise<{
        __kind__: "ok";
        ok: null;
    } | {
        __kind__: "err";
        err: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.submitFitness(arg0, arg1, arg2);
                return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitFitness(arg0, arg1, arg2);
            return from_candid_variant_n25(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_ArtifactType_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ArtifactType): ArtifactType {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Artifact_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Artifact): Artifact {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_TaskStatus_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _TaskStatus): TaskStatus {
    return from_candid_variant_n5(_uploadFile, _downloadFile, value);
}
function from_candid_Task_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Task): Task {
    return from_candid_record_n3(_uploadFile, _downloadFile, value);
}
function from_candid_WorkerStatus_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkerStatus): WorkerStatus {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Worker_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Worker): Worker {
    return from_candid_record_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Task]): Task | null {
    return value.length === 0 ? null : from_candid_Task_n2(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Worker]): Worker | null {
    return value.length === 0 ? null : from_candid_Worker_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Timestamp]): Timestamp | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Artifact]): Artifact | null {
    return value.length === 0 ? null : from_candid_Artifact_n7(_uploadFile, _downloadFile, value[0]);
}
function from_candid_record_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    elo: number;
    status: _WorkerStatus;
    slashCount: bigint;
    lastSubmission: [] | [_Timestamp];
    totalSubmissions: bigint;
}): {
    id: Principal;
    elo: number;
    status: WorkerStatus;
    slashCount: bigint;
    lastSubmission?: Timestamp;
    totalSubmissions: bigint;
} {
    return {
        id: value.id,
        elo: value.elo,
        status: from_candid_WorkerStatus_n17(_uploadFile, _downloadFile, value.status),
        slashCount: value.slashCount,
        lastSubmission: record_opt_to_undefined(from_candid_opt_n19(_uploadFile, _downloadFile, value.lastSubmission)),
        totalSubmissions: value.totalSubmissions
    };
}
function from_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _TaskId;
    modelArtifactId: _ArtifactId;
    status: _TaskStatus;
    currentGeneration: bigint;
    datasetArtifactId: _ArtifactId;
    createdAt: _Timestamp;
    createdBy: Principal;
    totalGenerations: bigint;
    updatedAt: _Timestamp;
    params: _EggrollParams;
}): {
    id: TaskId;
    modelArtifactId: ArtifactId;
    status: TaskStatus;
    currentGeneration: bigint;
    datasetArtifactId: ArtifactId;
    createdAt: Timestamp;
    createdBy: Principal;
    totalGenerations: bigint;
    updatedAt: Timestamp;
    params: EggrollParams;
} {
    return {
        id: value.id,
        modelArtifactId: value.modelArtifactId,
        status: from_candid_TaskStatus_n4(_uploadFile, _downloadFile, value.status),
        currentGeneration: value.currentGeneration,
        datasetArtifactId: value.datasetArtifactId,
        createdAt: value.createdAt,
        createdBy: value.createdBy,
        totalGenerations: value.totalGenerations,
        updatedAt: value.updatedAt,
        params: value.params
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ArtifactId;
    cid: string;
    verified: boolean;
    artifactType: _ArtifactType;
    contentHash: string;
    timestamp: _Timestamp;
    uploadedBy: Principal;
}): {
    id: ArtifactId;
    cid: string;
    verified: boolean;
    artifactType: ArtifactType;
    contentHash: string;
    timestamp: Timestamp;
    uploadedBy: Principal;
} {
    return {
        id: value.id,
        cid: value.cid,
        verified: value.verified,
        artifactType: from_candid_ArtifactType_n9(_uploadFile, _downloadFile, value.artifactType),
        contentHash: value.contentHash,
        timestamp: value.timestamp,
        uploadedBy: value.uploadedBy
    };
}
function from_candid_variant_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Task;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Task;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Task_n2(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ModelWeights: null;
} | {
    Kernel: null;
} | {
    Dataset: null;
} | {
    Config: null;
}): ArtifactType {
    return "ModelWeights" in value ? ArtifactType.ModelWeights : "Kernel" in value ? ArtifactType.Kernel : "Dataset" in value ? ArtifactType.Dataset : "Config" in value ? ArtifactType.Config : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Inactive: null;
} | {
    Active: null;
} | {
    Slashed: null;
}): WorkerStatus {
    return "Inactive" in value ? WorkerStatus.Inactive : "Active" in value ? WorkerStatus.Active : "Slashed" in value ? WorkerStatus.Slashed : value;
}
function from_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Artifact;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Artifact;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Artifact_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Worker;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Worker;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Worker_n15(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    Active: null;
} | {
    Cancelled: null;
} | {
    Completed: null;
} | {
    Pending: null;
}): TaskStatus {
    return "Active" in value ? TaskStatus.Active : "Cancelled" in value ? TaskStatus.Cancelled : "Completed" in value ? TaskStatus.Completed : "Pending" in value ? TaskStatus.Pending : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Artifact>): Array<Artifact> {
    return value.map((x)=>from_candid_Artifact_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Task>): Array<Task> {
    return value.map((x)=>from_candid_Task_n2(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Worker>): Array<Worker> {
    return value.map((x)=>from_candid_Worker_n15(_uploadFile, _downloadFile, x));
}
function to_candid_ArtifactType_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArtifactType): _ArtifactType {
    return to_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ArtifactType): {
    ModelWeights: null;
} | {
    Kernel: null;
} | {
    Dataset: null;
} | {
    Config: null;
} {
    return value == ArtifactType.ModelWeights ? {
        ModelWeights: null
    } : value == ArtifactType.Kernel ? {
        Kernel: null
    } : value == ArtifactType.Dataset ? {
        Dataset: null
    } : value == ArtifactType.Config ? {
        Config: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
